# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1al8ZVQ48iw4dP2363XQo5DM6GnsHmmKB

# YouTube Engagement Trends Dashboard for Vivid-Sync Media

This notebook prepares the YouTube trending videos dataset for Tableau analysis focused on engagement score, category comparison, and trend analysis.
"""

import pandas as pd
import numpy as np

"""## Load the dataset"""

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("CAvideos.csv")
df.head()

"""## Check the dataset shape and columns"""

print(df.shape)
print(df.columns.tolist())

"""## Check missing values in the main fields"""

main_fields = [
    "trending_date",
    "title",
    "channel_title",
    "category_id",
    "publish_time",
    "views",
    "likes",
    "comment_count"
]

print(df[main_fields].isnull().sum())

"""## Preview the core analysis fields"""

df[[
    "trending_date",
    "title",
    "channel_title",
    "category_id",
    "views",
    "likes",
    "comment_count"
]].head(15)

"""## Check basic numeric ranges"""

df[[
    "views",
    "likes",
    "comment_count"
]].describe()

"""## Create a simple source region field

Since this file is the Canada trending file, we label the source region clearly.
"""

df["Region"] = "Canada"
df[["title", "Region"]].head()

"""# Step 2: Clean the dataset and create Tableau-ready time fields

In this step, we clean the core YouTube fields, convert the date columns, ensure numeric columns are valid, and create helper fields for time-based Tableau analysis.

## Keep only the fields needed for the project
"""

columns_needed = [
    "video_id",
    "trending_date",
    "title",
    "channel_title",
    "category_id",
    "publish_time",
    "views",
    "likes",
    "comment_count",
    "Region"
]

df = df[columns_needed].copy()
df.head()

"""## Remove rows with missing values in the core fields"""

df = df.dropna(subset=[
    "trending_date",
    "title",
    "channel_title",
    "category_id",
    "publish_time",
    "views",
    "likes",
    "comment_count"
]).copy()

print(df.shape)

"""## Convert the numeric fields to numeric type"""

for col in ["views", "likes", "comment_count", "category_id"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df[["views", "likes", "comment_count", "category_id"]].dtypes)

"""## Remove rows that became invalid after numeric conversion"""

df = df.dropna(subset=["views", "likes", "comment_count", "category_id"]).copy()
print(df.shape)

"""## Convert publish time to datetime"""

df["publish_time"] = pd.to_datetime(df["publish_time"], errors="coerce")
print(df["publish_time"].dtype)

"""## Convert trending date to datetime

The trending_date field in this dataset uses a short year format like YY.DD.MM.
"""

df["trending_date"] = pd.to_datetime(df["trending_date"], format="%y.%d.%m", errors="coerce")
print(df["trending_date"].dtype)

"""## Remove rows with invalid converted dates"""

df = df.dropna(subset=["publish_time", "trending_date"]).copy()
print(df.shape)

"""## Create helper date fields for Tableau"""

df["Trending_Month"] = df["trending_date"].dt.to_period("M").astype(str)
df["Trending_Week"] = df["trending_date"].dt.to_period("W").astype(str)
df["Trending_Year"] = df["trending_date"].dt.year

df[["trending_date", "Trending_Month", "Trending_Week", "Trending_Year"]].head()

"""## Preview the cleaned dataset"""

print(df.shape)
df.head()

"""# Step 3: Create category labels and save the Tableau-ready dataset

In this step, we map the YouTube category IDs to readable category names, create a cleaner category field for Tableau, and save the final dataset.

## Map category IDs to readable YouTube category names
"""

category_map = {
    1: "Film & Animation",
    2: "Autos & Vehicles",
    10: "Music",
    15: "Pets & Animals",
    17: "Sports",
    18: "Short Movies",
    19: "Travel & Events",
    20: "Gaming",
    21: "Videoblogging",
    22: "People & Blogs",
    23: "Comedy",
    24: "Entertainment",
    25: "News & Politics",
    26: "Howto & Style",
    27: "Education",
    28: "Science & Technology",
    29: "Nonprofits & Activism",
    30: "Movies",
    31: "Anime/Animation",
    32: "Action/Adventure",
    33: "Classics",
    34: "Comedy",
    35: "Documentary",
    36: "Drama",
    37: "Family",
    38: "Foreign",
    39: "Horror",
    40: "Sci-Fi/Fantasy",
    41: "Thriller",
    42: "Shorts",
    43: "Shows",
    44: "Trailers"
}

df["Category"] = df["category_id"].map(category_map).fillna("Other")
df[["category_id", "Category"]].drop_duplicates().sort_values("category_id").head(20)

"""## Check category distribution"""

df["Category"].value_counts().head(20)

"""## Standardize text fields"""

for col in ["title", "channel_title", "Category", "Region"]:
    df[col] = df[col].astype(str).str.strip()

df.head()

"""## Optional: check for zero-view rows

This matters because the Engagement Score in Tableau must avoid division by zero.
"""

print("Rows with zero views:", (df["views"] == 0).sum())

"""## Preview the final Tableau-ready fields"""

df[[
    "video_id",
    "trending_date",
    "Trending_Month",
    "Trending_Week",
    "Trending_Year",
    "title",
    "channel_title",
    "Category",
    "views",
    "likes",
    "comment_count",
    "Region"
]].head(20)

"""## Save the final Tableau-ready dataset"""

df.to_csv("youtube_engagement_ready.csv", index=False)
print("Saved as youtube_engagement_ready.csv")

from google.colab import files
files.download("youtube_engagement_ready.csv")