# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1353BVIOgWtU7zbBKb6jTj_QtxSTlZHLa

# Capoeira & Combat Studio: Member Retention Cohort Analysis

This notebook prepares a public customer churn dataset to simulate a martial arts studio membership-retention dashboard for Tableau.
"""

import pandas as pd
import numpy as np

from google.colab import files
files.upload()

"""## Load the dataset"""

df = pd.read_csv("customer_churn_dataset-testing-master.csv")
df.head()

"""## Check the dataset shape and columns"""

print(df.shape)
print(df.columns.tolist())

"""## Clean the column names"""

df.columns = (
    df.columns
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

for col in df.columns:
    print(repr(col))

"""## Preview the main retention fields"""

df[[
    "CustomerID",
    "Tenure",
    "Subscription Type",
    "Contract Length",
    "Total Spend",
    "Churn"
]].head(15)

"""## Check missing values in the main fields"""

print(df[[
    "CustomerID",
    "Tenure",
    "Subscription Type",
    "Contract Length",
    "Total Spend",
    "Churn"
]].isnull().sum())

"""## Check basic distributions"""

print(df["Churn"].value_counts(dropna=False))
print(df["Subscription Type"].value_counts(dropna=False))
print(df["Contract Length"].value_counts(dropna=False))

"""## Check the tenure and spend ranges"""

df[["Tenure", "Total Spend"]].describe()

"""# Step 2: Clean the dataset and create studio-style membership fields

In this step, we clean the core churn fields and create the simulated studio membership dimensions needed for cohort analysis.

## Keep only the fields needed for the project
"""

columns_needed = [
    "CustomerID",
    "Tenure",
    "Subscription Type",
    "Contract Length",
    "Total Spend",
    "Churn"
]

df = df[columns_needed].copy()
df.head()

"""## Remove rows with missing values in the core fields"""

df = df.dropna(subset=[
    "CustomerID",
    "Tenure",
    "Subscription Type",
    "Contract Length",
    "Total Spend",
    "Churn"
]).copy()

print(df.shape)

"""## Convert tenure and spend to numeric"""

df["Tenure"] = pd.to_numeric(df["Tenure"], errors="coerce")
df["Total Spend"] = pd.to_numeric(df["Total Spend"], errors="coerce")

print(df[["Tenure", "Total Spend"]].dtypes)

"""## Remove rows that became invalid after numeric conversion"""

df = df.dropna(subset=["Tenure", "Total Spend"]).copy()
print(df.shape)

"""## Standardize the text fields"""

for col in ["Subscription Type", "Contract Length", "Churn"]:
    df[col] = df[col].astype(str).str.strip()

df.head()

"""## Create a simulated Program Type field

This simulates Capoeira vs Boxing membership tracks.
"""

programs = ["Capoeira", "Boxing"]
df["Program_Type"] = [programs[i % len(programs)] for i in range(len(df))]

df[["CustomerID", "Program_Type"]].head()

"""## Create a Membership Tier field

This repurposes the subscription structure into a studio-style tier.
"""

def map_membership_tier(sub_type, contract):
    s = str(sub_type).lower()
    c = str(contract).lower()

    if "premium" in s or "annual" in c:
        return "Premium"
    elif "standard" in s or "quarter" in c:
        return "Standard"
    else:
        return "Basic"

df["Membership_Tier"] = df.apply(
    lambda row: map_membership_tier(row["Subscription Type"], row["Contract Length"]),
    axis=1
)

df[["Subscription Type", "Contract Length", "Membership_Tier"]].drop_duplicates()

"""## Create Enrollment Year and Join Date

Since the source dataset does not include real join dates, we simulate them in a realistic way using tenure.
"""

analysis_date = pd.Timestamp("2025-01-01")

df["Tenure"] = df["Tenure"].astype(int)
df["Join_Date"] = analysis_date - pd.to_timedelta(df["Tenure"] * 30, unit="D")
df["Enrollment_Year"] = df["Join_Date"].dt.year
df["Cohort_Month"] = df["Join_Date"].dt.to_period("M").astype(str)

df[["CustomerID", "Tenure", "Join_Date", "Enrollment_Year", "Cohort_Month"]].head()

"""## Create a Retained Flag

This will support the retention matrix later.
"""

df["Retained_Flag"] = np.where(df["Churn"].str.lower().isin(["yes", "churned", "true", "1"]), 0, 1)

df[["Churn", "Retained_Flag"]].drop_duplicates()

"""## Preview the cleaned membership-style dataset"""

print(df.shape)
df.head()

"""# Step 3: Create retention and churn helper fields for Tableau

In this step, we create the retention-analysis fields needed to support the cohort heatmap, churn velocity analysis, and dashboard filters in Tableau.

## Create Months Since Join

This gives us the cohort timeline position for each member.
"""

df["Months_Since_Join"] = df["Tenure"].astype(int)
df[["CustomerID", "Tenure", "Months_Since_Join"]].head()

"""## Create a churn velocity band

This groups churn timing into early, mid, and late dropout behavior.
"""

def churn_velocity_band(row):
    if row["Retained_Flag"] == 1:
        return "Still Active"
    elif row["Months_Since_Join"] <= 3:
        return "Early Churn"
    elif row["Months_Since_Join"] <= 8:
        return "Mid Churn"
    else:
        return "Late Churn"

df["Churn_Velocity"] = df.apply(churn_velocity_band, axis=1)
df["Churn_Velocity"].value_counts()

"""## Create a cohort month date field

This is useful for sorting cohort months properly in Tableau.
"""

df["Cohort_Month_Date"] = pd.to_datetime(df["Cohort_Month"] + "-01")
df[["Cohort_Month", "Cohort_Month_Date"]].head()

"""## Create a current active status field"""

df["Member_Status"] = np.where(df["Retained_Flag"] == 1, "Active", "Churned")
df[["Retained_Flag", "Member_Status"]].drop_duplicates()

"""## Create a spend band field

This can support deeper segmentation or extra EDA later.
"""

def spend_band(spend):
    if spend >= 1000:
        return "High Spend"
    elif spend >= 500:
        return "Medium Spend"
    else:
        return "Low Spend"

df["Spend_Band"] = df["Total Spend"].apply(spend_band)
df["Spend_Band"].value_counts()

"""## Check the main analysis dimensions"""

print(df["Program_Type"].value_counts())
print(df["Membership_Tier"].value_counts())
print(df["Enrollment_Year"].value_counts().sort_index())
print(df["Churn_Velocity"].value_counts())

"""## Preview the Tableau-ready retention dataset"""

df[[
    "CustomerID",
    "Program_Type",
    "Membership_Tier",
    "Join_Date",
    "Enrollment_Year",
    "Cohort_Month",
    "Cohort_Month_Date",
    "Months_Since_Join",
    "Retained_Flag",
    "Member_Status",
    "Churn_Velocity",
    "Total Spend"
]].head(20)

"""## Save the final Tableau-ready dataset"""

df.to_csv("combat_studio_retention_ready.csv", index=False)
print("Saved as combat_studio_retention_ready.csv")

from google.colab import files
files.download("combat_studio_retention_ready.csv")